# Generated by Django 4.1 on 2024-03-02 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rtchatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
